name: Eli
favicon: null
layout_spectrum: 0.0449574061203748
typography_spectrum: 0.7903492709156126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8743155645206571
  lightness: 0.6133351882454008
  saturation: 0.09264321019873023
  rhythmicContrast: 0.7014984921552241
purpose: []
